name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh "hamza-testing-bucket" "/mystyle.css" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "mystyle.css"